CREATE TABLE OGRENCI_BILGI(
	OGRENCI_ID varchar(11) PRIMARY KEY,
	OGRENCI_TC varchar(11),
	OGRENCI_NO varchar(11),
	OGRENCI_AD nvarchar(50),
	OGRENCI_SOYAD nvarchar(50),
	OGRENCI_MAIL nvarchar(50)
)	