use EGEVERITABANI
insert into DANISMAN(DANISMAN_ID,OGRETMEN_ID,DANISMAN_AD,DANISMAN_SOYAD,BOLUM_ID)
VALUES
('DANISMAN1','OGRTMN110','Ferzan','Özkartal','101'),
('DANISMAN2','OGRTMN111','Zerrin','Aktaþ','102'),
('DANISMAN3','OGRTMN112','Barlas','Yorgun','103'),
('DANISMAN4','OGRTMN113','Nermin','Yenilmez','104'),
('DANISMAN5','OGRTMN114','Yalýn','Serin','105')