use EGEVERITABANI
INSERT INTO DERS_PROGRAM (DERS_ID, DERS_AD, OGRETMEN_AD, OGRETMEN_SOYAD, GUN, SAAT, SINIF)
VALUES (1001, 'MATEMATÝK', 'Ferzan', 'Özkartal', 'Pazartesi 1.', '09:00:00', '1.SINIF')

INSERT INTO DERS_PROGRAM (DERS_ID, DERS_AD, OGRETMEN_AD, OGRETMEN_SOYAD, GUN, SAAT, SINIF)
VALUES (1002, 'DOÐRU AKIM DEVRELERÝ', 'Ferzan', 'Özkartal', 'Pazartesi 2.', '10:00:00', '1.SINIF')

INSERT INTO DERS_PROGRAM (DERS_ID, DERS_AD, OGRETMEN_AD, OGRETMEN_SOYAD, GUN, SAAT, SINIF)
VALUES (1003, 'FÝZÝK', 'Ferzan', 'Özkartal', 'Pazartesi 3.', '11:00:00', '1.SINIF')

INSERT INTO DERS_PROGRAM (DERS_ID, DERS_AD, OGRETMEN_AD, OGRETMEN_SOYAD, GUN, SAAT, SINIF)
VALUES (1004, 'ÖLÇME TEKNÝÐÝ', 'Ferzan', 'Özkartal', 'Pazartesi 4.', '12:00:00', '1.SINIF')

INSERT INTO DERS_PROGRAM (DERS_ID, DERS_AD, OGRETMEN_AD, OGRETMEN_SOYAD, GUN, SAAT, SINIF)
VALUES (1005, 'KARÝYER PLANLAMA', 'Ferzan', 'Özkartal', 'Pazartesi 5.', '13:00:00', '1.SINIF')

INSERT INTO DERS_PROGRAM (DERS_ID, DERS_AD, OGRETMEN_AD, OGRETMEN_SOYAD, GUN, SAAT, SINIF)
VALUES (1006, 'ÜNÝVERSÝTE YAÞAMINA GEÇÝÞ', 'Ferzan', 'Özkartal', 'Salý 1.', '09:00:00', '1.SINIF')

INSERT INTO DERS_PROGRAM (DERS_ID, DERS_AD, OGRETMEN_AD, OGRETMEN_SOYAD, GUN, SAAT, SINIF)
VALUES (1007, 'ATATÜRK Ý.Ý.T.-1', 'Ferzan', 'Özkartal', 'Salý 2.', '10:00:00', '1.SINIF')

INSERT INTO DERS_PROGRAM (DERS_ID, DERS_AD, OGRETMEN_AD, OGRETMEN_SOYAD, GUN, SAAT, SINIF)
VALUES (1008, 'BÝLGÝSAYAR', 'Ferzan', 'Özkartal', 'Çarþamba 1.', '11:00:00', '1.SINIF')

INSERT INTO DERS_PROGRAM (DERS_ID, DERS_AD, OGRETMEN_AD, OGRETMEN_SOYAD, GUN, SAAT, SINIF)
VALUES (1009, 'TEMEL ELEKTRONÝK', 'Ferzan', 'Özkartal', 'Çarþamba 2.', '12:00:00', '1.SINIF')

INSERT INTO DERS_PROGRAM (DERS_ID, DERS_AD, OGRETMEN_AD, OGRETMEN_SOYAD, GUN, SAAT, SINIF)
VALUES (1010, 'TÜRK DÝLÝ-1', 'Ferzan', 'Özkartal', 'Perþembe', '13:00:00', '1.SINIF')

INSERT INTO DERS_PROGRAM (DERS_ID, DERS_AD, OGRETMEN_AD, OGRETMEN_SOYAD, GUN, SAAT, SINIF)
VALUES (1011, 'YABANCI DÝL-1', 'Ferzan', 'Özkartal', 'Cuma', '14:00:00', '1.SINIF')