CREATE TABLE YEMEKLER (
	YEMEKHANE_ID varchar(11) primary key,
    GUN VARCHAR(20),
    KAHVALTI VARCHAR(200),
    KAHVALTISAAT VARCHAR(20),
    OGLENYEMEGI VARCHAR(200),
    OGLENYEMEGISAAT VARCHAR(20),
    AKSAMYEMEGI VARCHAR(200),
    AKSAMYEMEGISAAT VARCHAR(20)
)